#!/usr/bin/env bash

clean() {
  say "Let's clean up this mess..."
  rm -rf build > /dev/null 2>&1
}

conf() {
  say "Time to configure this beast..."
  local generator=${1:-unix}
  if [ "$generator" == "ninja" ]; then
    say "Ninja mode! Yaiii!"
    cmake -B build -S . -G Ninja
  else
    say "Using Unix Makefiles...bleh!"  
    cmake -B build -S . -G "Unix Makefiles"
  fi

  if [ $? -ne 0 ]; then
    say "Configuration failed!"
    exit 1
  fi
}

build() {
  say "Let's see if this builds..."
  if ! cmake --build build --parallel 3; then
    say "Build failed!"
    exit 1
  fi
}

doall() {
  local generator=${1:-unix}
  say  "you made a mess, uh? Let me do it for you..."
  clean
  conf "$generator"
  build
}

# Clear terminal screen and remove old log files
clear
rm -f logs/*.log > /dev/null 2>&1

case "$1" in
  clean)
    clean
    ;;
  conf)
    conf "$2"
    ;;
  build)
    build
    ;;
  doall)
    doall "$2"
    ;;
  *)
    [ ! -d "build" ] && conf "unix"
    build
    ;;
esac

say "All done, finally!"
if [ $? -ne 0 ]; then
  say "That was painful dude!"
  exit 1
else
  say "You're good to go!"
  exit 0
fi