#!/usr/bin/env bash

clean() {
  say "Cleaning up..."
  rm -rf build > /dev/null 2>&1
}

conf() {
  say "Configuring..."
  local generator=$1
  if [ "$generator" == "ninja" ]; then
    say "Ninja mode on!"
    cmake -B build -S . -G Ninja
  else
    say "Using Unix Makefiles..."
    cmake -B build -S . -G "Unix Makefiles"
  fi

  if [ $? -ne 0 ]; then
    say "Config failed! Exiting!"
    exit 1
  fi
}

build() {
  say "Building..."
  if ! cmake --build build --parallel 3; then
    say "Build error!"
    say "Aborting build!"
    exit 1
  fi
}

# Clear terminal screen and remove old log files
clear
rm -f logs/*.log > /dev/null 2>&1

case "$1" in
  clean)
    clean
    ;;
  conf)
    conf "$2"
    ;;
  *)
    [ ! -d "build" ] && conf "unix"
    build
    ;;
esac

say "All done!"